"""Four-word session ID generator.

Produces IDs like ``quiet-otter-builds-kites`` by combining an adjective,
a subject noun, a verb, and an object noun. Each word list has 64 entries,
giving ~16 million unique combinations before collisions.
"""

import secrets

from psoul.core.session import validate_session_id

ADJECTIVES: tuple[str, ...] = (
    "agile",
    "airy",
    "alert",
    "amber",
    "brave",
    "bright",
    "brisk",
    "calm",
    "clear",
    "clever",
    "cool",
    "crisp",
    "daring",
    "deft",
    "eager",
    "fancy",
    "fleet",
    "fresh",
    "gentle",
    "glad",
    "golden",
    "grand",
    "happy",
    "hasty",
    "keen",
    "kind",
    "lively",
    "lucky",
    "merry",
    "mild",
    "minty",
    "nimble",
    "noble",
    "pearl",
    "plucky",
    "proud",
    "quick",
    "quiet",
    "rapid",
    "ready",
    "rosy",
    "royal",
    "sandy",
    "sharp",
    "shiny",
    "silken",
    "silver",
    "sleek",
    "smart",
    "smooth",
    "snug",
    "soft",
    "spry",
    "starlit",
    "steady",
    "sunny",
    "swift",
    "tidy",
    "tranquil",
    "true",
    "velvet",
    "vivid",
    "warm",
    "wise",
)

SUBJECT_NOUNS: tuple[str, ...] = (
    "badger",
    "beaver",
    "bobcat",
    "canary",
    "cougar",
    "coyote",
    "cricket",
    "falcon",
    "ferret",
    "finch",
    "fox",
    "gecko",
    "gopher",
    "heron",
    "ibis",
    "jaguar",
    "kingfisher",
    "lark",
    "lemur",
    "leopard",
    "lynx",
    "magpie",
    "marten",
    "meerkat",
    "mockingbird",
    "mole",
    "narwhal",
    "ocelot",
    "oriole",
    "otter",
    "owl",
    "panda",
    "panther",
    "parrot",
    "pelican",
    "penguin",
    "phoenix",
    "pika",
    "puffin",
    "quail",
    "rabbit",
    "raccoon",
    "ram",
    "raven",
    "robin",
    "seal",
    "sparrow",
    "stoat",
    "swan",
    "thrush",
    "tiger",
    "toucan",
    "turtle",
    "viper",
    "walrus",
    "weasel",
    "whale",
    "wildcat",
    "wolf",
    "wombat",
    "wren",
    "yak",
    "zorilla",
    "kite",
)

OBJECT_NOUNS: tuple[str, ...] = (
    "acorns",
    "arrows",
    "banners",
    "barrels",
    "beacons",
    "berries",
    "blankets",
    "blooms",
    "boats",
    "books",
    "bridges",
    "brooms",
    "buckets",
    "candles",
    "cards",
    "charms",
    "clocks",
    "comets",
    "crates",
    "crowns",
    "drums",
    "feathers",
    "flags",
    "flowers",
    "flutes",
    "fruits",
    "garlands",
    "gems",
    "gloves",
    "hammers",
    "helmets",
    "kites",
    "ladles",
    "lanterns",
    "letters",
    "maps",
    "mirrors",
    "needles",
    "orbits",
    "oars",
    "petals",
    "pebbles",
    "pennants",
    "pillows",
    "pinecones",
    "ribbons",
    "rings",
    "ropes",
    "saddles",
    "sails",
    "scarves",
    "shells",
    "shields",
    "songs",
    "sparks",
    "stars",
    "stones",
    "tables",
    "tickets",
    "trophies",
    "trumpets",
    "wheels",
    "windows",
    "wreaths",
)

VERBS: tuple[str, ...] = (
    "admires",
    "arranges",
    "builds",
    "carries",
    "charts",
    "chases",
    "chooses",
    "collects",
    "counts",
    "crafts",
    "draws",
    "finds",
    "folds",
    "follows",
    "forges",
    "gathers",
    "greets",
    "guides",
    "holds",
    "keeps",
    "kicks",
    "lifts",
    "lights",
    "loads",
    "maps",
    "marks",
    "mends",
    "moves",
    "names",
    "orders",
    "paints",
    "passes",
    "plants",
    "polishes",
    "pulls",
    "raises",
    "reads",
    "rescues",
    "rings",
    "rolls",
    "sails",
    "saves",
    "seeks",
    "shapes",
    "shares",
    "signals",
    "sketches",
    "sorts",
    "spins",
    "spots",
    "stacks",
    "stirs",
    "stores",
    "strings",
    "studies",
    "swaps",
    "tends",
    "tracks",
    "trades",
    "turns",
    "weaves",
    "wins",
    "wraps",
    "writes",
)


def generate_session_id() -> str:
    """Generate a random four-word session ID like ``quiet-otter-builds-kites``.

    Picks one word from each of the four 64-entry word lists using
    ``secrets.choice`` for uniform randomness.  The result is validated
    against ``validate_session_id`` before returning.

    Returns:
        str: A hyphen-joined four-word session ID.

    """
    session_id = "-".join(
        (
            secrets.choice(ADJECTIVES),
            secrets.choice(SUBJECT_NOUNS),
            secrets.choice(VERBS),
            secrets.choice(OBJECT_NOUNS),
        )
    )
    validate_session_id(session_id)
    return session_id
